env:
  devO
server:
  port: 8811
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&useSSL=true
    username: root
    password: 123456
  application:
    name: order
  jpa:
    show-sql: true


