spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaomingaZz/cloudConfig.git
          username: xiaomingZz
          password: tumingshishao
  application:
    name: config
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka-server

server:
  port: 8810

lable:
  release
env:
  dev
